## ODS competition autumn 2025

In [2]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

from sklearn.linear_model import LogisticRegression, Ridge, Lasso
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, VotingClassifier
from sklearn.model_selection import train_test_split, GridSearchCV, RandomizedSearchCV, cross_val_score
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.metrics import classification_report, roc_auc_score, mean_squared_error, r2_score, accuracy_score, confusion_matrix, RocCurveDisplay, PrecisionRecallDisplay
from sklearn.inspection import PartialDependenceDisplay
from sklearn.compose import ColumnTransformer, make_column_selector

from catboost import CatBoostClassifier

import eli5
from eli5.sklearn import PermutationImportance

import shap
from shap import TreeExplainer

In [5]:
df_train = pd.read_csv('train_final.csv', index_col=0)

In [6]:
df_train.head()

   user_id                   ts  gate_id
0       18  2022-07-29 09:08:54        7
1       18  2022-07-29 09:09:54        9
2       18  2022-07-29 09:09:54        9
3       18  2022-07-29 09:10:06        5
4       18  2022-07-29 09:10:08        5

In [7]:
df_test = pd.read_csv('test_final.csv', index_col=0)
df_test.head()

                        ts  gate_id user_word
37518  2023-01-03 08:21:00        9      gini
37519  2023-01-03 08:21:00        9      gini
37520  2023-01-03 08:21:18        5      gini
37521  2023-01-03 08:21:19        5      gini
37522  2023-01-03 08:21:39       10      gini

In [ ]:
df.shifted_hour = df['hour'] + 1  df['shifted_hour'] = df['shifted_hour'] % 24
df['hour_sin'] = np.sin(2 * np.pi * df['hour'] / 24)  df['hour_cos'] = np.cos(2 * np.pi * df['hour'] / 24)

# Remove rows with NaN created by shift()
df_clean = df.dropna()
# Or use reset_index to fix index after removal
df_clean = df.dropna().reset_index(drop=True)

In [ ]:
from sklearn.impute import SimpleImputer  imp = SimpleImputer(strategy='mean')  df[num_cols] = imp.fit_transform(df[num_cols])

In [ ]:
sns.kdeplot(df[df[pred].isna()][target], label='NaN') sns.kdeplot(df[df[pred].notna()][target], label='No NaN')
# MCAR if different → no MCAR.
# How to convert predictions back from differences?
y_restored = y_train_last + np.cumsum(y_diff_pred)